import {
  bool,
  date,
  email,
  nint,
  nnum,
  nobject,
  nstr,
  ndate,
  num,
  object,
  str
} from './builders.js';

export const crmContracts = {
  'crm.employees': object({
    _id: str,
    sourceUserId: str,
    email,
    name: str,
    sourceRole: nstr,
    active: bool,
    srcCreatedAt: ndate,
    srcUpdatedAt: date
  }),
  'crm.customers': object({
    _id: str,
    sourceCustomerId: str,
    name: str,
    customerType: nstr,
    state: nstr,
    managedByEmployeeId: nstr,
    managedBySourceId: nstr,
    active: bool,
    srcCreatedAt: ndate,
    srcUpdatedAt: date
  }),
  'crm.connections': object({
    _id: str,
    opportunityId: nstr,
    customerId: nstr,
    customerSourceId: nstr,
    createdByEmployeeId: nstr,
    approvedByEmployeeId: nstr,
    activatedByEmployeeId: nstr,
    serviceType: nstr,
    bandwidthRaw: nstr,
    bandwidthMbps: num,
    bandwidthParsed: bool,
    telcoProvider: nstr,
    status: str,
    mrcPaise: nint,
    otcPaise: nint,
    providerMrcPaise: nint,
    marginMrcPaise: nint,
    ipCount: nint,
    ipCostPaise: nint,
    aEndBtsId: nstr,
    bEndBtsId: nstr,
    acceptanceDate: ndate,
    remarksSnippet: nstr,
    termination: nobject({ raiseDate: ndate, finalDate: ndate, reasonSnippet: nstr }),
    rejection: nobject({ rejectedAt: ndate, reasonSnippet: nstr }),
    srcCreatedAt: ndate,
    srcUpdatedAt: date
  }),
  'crm.connection_events': object({
    _id: str,
    connectionId: str,
    action: str,
    date: ndate,
    performedByEmployeeId: nstr,
    bandwidthRaw: nstr,
    bandwidthMbps: nnum,
    mrcPaise: nint,
    noteSnippet: nstr,
    parentUpdatedAt: date
  }),
  'crm.service_requests': object({
    _id: str,
    customerId: nstr,
    customerSourceId: nstr,
    requestType: nstr,
    status: nstr,
    serviceType: nstr,
    bandwidthCurrentMbps: nnum,
    bandwidthRequestedMbps: nnum,
    mrcPaise: nint,
    createdByEmployeeId: nstr,
    approvedByEmployeeId: nstr,
    disconnectionReasonSnippet: nstr,
    raiseDate: ndate,
    finalDisconnectionDate: ndate,
    srcCreatedAt: ndate,
    srcUpdatedAt: date
  }),
  'crm.sales_targets': object({
    _id: str,
    employeeId: nstr,
    employeeSourceId: str,
    monthKey: { type: 'string', pattern: '^\\d{4}-(0[1-9]|1[0-2])$' },
    monthStart: date,
    targetMbps: num,
    setByEmployeeId: nstr,
    srcUpdatedAt: date
  })
};
